Api management
Sauti-Africa/sauti-africa-market-price-data-be pull request #2
Opened 2020-01-09 22:10 UTC by mxxt1

# Description

This feature prevents users from abusing the API by linking the call count to the user id instead of the api key itself. This allows users to generate a new key if they've lost their existing key without circumventing the quota enforcement system. 

###Redis: 

Refactors the existing API key generation functionality to link api call count to the user id. When a key is generated, the system checks for an existing entry using the user id. If a record exists for that user id, the new hashed key overwrites the existing hashed key, and sends the plain-text api key to the frontend, and stays visible during that session.
 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [x] Complete, but not tested (may need new tests)
- [x] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Postman
- [ ] Test B

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2020-01-14 23:08 UTC, blackmacaroon commented on __tests__/Routes/Routes/Users/userRoles.spec.js
> +                    // console.log('LOGGING', result, data)
so proud of myself for commenting the whole pr, did it on the og repo. 🤦‍♀  
bold addition of extra space, I'm all about aesthetics.

2020-01-14 23:10 UTC, blackmacaroon commented on README.md
> +
so proud of myself for commenting the whole PR, dummy did it on the OG repo 🤦‍♀ 
bold addition of extra space, I'm all about aesthetics.

2020-01-14 23:11 UTC, blackmacaroon commented on __tests__/Routes/Routes/Users/userRoles.spec.js
> +                    // console.log('LOGGING', result, data)
maybe it's a console log for testing, test it and delete it. maybe it's for future devs, leave a comment about why they'll need to console log.

2020-01-14 23:12 UTC, blackmacaroon commented on api-key/migrations/20191018164134_create-apiKey-table.js
> +    //reset_date stores the date as milliseconds as an integer
excellent use of comment to clarify potentially confusing code

2020-01-14 23:12 UTC, blackmacaroon commented on api/server.js
> +// TODO: POSSIBL CODE CLEANUP WITH BELOW IMPORTS, AS THEIR NOT BEING USED.
if we're not using it, delete it. Or, as I believe the kids are calling it these days: "yeet"

2020-01-14 23:13 UTC, blackmacaroon commented on api/server.js
> +
yeet

2020-01-14 23:15 UTC, blackmacaroon commented on middleware/api-limiter-middleware.js
> +};
excellent use of comments as notes for future devs

2020-01-14 23:18 UTC, blackmacaroon commented on middleware/bottle.js
> +import Bottleneck from "bottleneck";
did we end up actually using Bottleneck? If not, we can go ahead and delete this whole thing.

2020-01-14 23:18 UTC, blackmacaroon commented on middleware/rules/rules-middleware.js
> +    // console.log(apiToken)
for testing or for devs? "no console logs in final code" but I don't hate commented out console logs with explanations in certain situations. Best Practice? Who knows.

2020-01-14 23:20 UTC, blackmacaroon commented on __tests__/Routes/Routes/Users/userRoles.spec.js
> +                    expect(!!data.app_metadata.role).toBe(true)
I had to look up double exclamation, I think I like it, but idk if I get it. It forces a value to behave like a boolean? fancy dev stuff here.

2020-01-14 23:22 UTC, blackmacaroon commented on middleware/token-middleware.js
> +}
If I learned anything in Labs it was: async all the things!

2020-01-14 23:47 UTC, blackmacaroon commented on redis/index.js
> +//this method is no longer applicable with user tiering. Reset periods are now determined by the api key registration date, and calculating 30 day intervals based on that initial generation date
what's no longer applicable?

2020-01-23 20:35 UTC, blackmacaroon commented on currency/index.js
> +      // console.log(`rates`,rates)
why do i need it or delete it

2020-01-23 20:35 UTC, blackmacaroon commented on developer/developer-router.js
> +// { apiCount: parseInt(req.count) }
souvenir?

2020-01-23 20:36 UTC, blackmacaroon commented on developer/developer-router.js
> +                // console.log(filtered)
yeet

2020-01-23 20:36 UTC, blackmacaroon commented on developer/developer-router.js
> +              // console.log(`converted: `,converted)
yeet

2020-01-23 20:37 UTC, blackmacaroon commented on developer/developer-router.js
>  //requires further validation possibly with moment.js to validate the date values//stretch goal for later
lets note this in the Notion Doc - Possible Future Stuff and Things

2020-01-23 20:39 UTC, blackmacaroon commented on middleware/time-period-middleware.js
> +    // console.log(`time period middleware`,req)
yeet

2020-01-23 22:10 UTC, Sauti-Africa commented on developer/developer-router.js
> +        console.log(`records product range `,records)
is this necessary or for testing?

2020-01-23 22:14 UTC, Sauti-Africa requested changes
A couple ToDo notes, lets transfer these to trello/notion (with file name and line #) and clean up and testing console.logs before we merge to master.
Are we using the middleware/bottle.js or is that a remnant from Igor? Lets delete whole dern file.

2020-01-24 17:27 UTC, merged