Pagination
Sauti-Africa/sauti-africa-market-price-data-be pull request #3
Opened 2020-01-28 20:34 UTC by mxxt1

# Description

Will complete this later this week. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2020-01-31 20:23 UTC, blackmacaroon requested changes

2020-01-31 20:23 UTC, blackmacaroon commented on developer/developer-model.js
> +  console.log('BOOKSHELF DATA PULL', await new shelfData().fetchAll().then(res => res.toJSON()))
do we need this console log deployed?

2020-01-31 20:23 UTC, blackmacaroon commented on developer/developer-model.js
> +    // console.log(await typeof queryOperation)
log

2020-01-31 20:23 UTC, blackmacaroon commented on developer/developer-model.js
> +    // console.log(await queryOperation)
log

2020-01-31 20:23 UTC, blackmacaroon commented on developer/developer-model.js
> +    console.log('DATES', startDate, endDate)
log

2020-01-31 20:23 UTC, blackmacaroon commented on developer/developer-model.js
> +    console.log((await queryOperation).length)
log

2020-01-31 20:23 UTC, blackmacaroon commented on developer/developer-model.js
> +    // TODO: COMPLETE MANUAL FUNCTION FOR ORGANIZING A COMPLETE SET OF TRAVERSING DATA OBEJCT.
don't forget to clear Todo's

2020-02-03 22:14 UTC, closed without merging

2020-02-03 22:14 UTC, mxxt1 commented
This branch is outmoded. Work was done on the express-pagination branch.